language: node_js

branches:
  only:
  - dev  # 设置自动化部署的源码分支


before_install:
- export TZ='Asia/Shanghai'  # 设置时区
- npm install -g hexo
- npm install -g hexo-cli
before_script:
# 设置github账户信息
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "caunong" #设置github用户名
- git config --global user.email caunong@live.com #设置github用户邮箱
# github仓库操作
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy
env:
 global:
   - GH_REF: github.com/caunong/caunong.github.io.git